name: Doplarr
version: "0.0.1"
panel_icon: "mdi:z-wave"
panel_title: Doplarr
slug: Doplarr
description: Doplarr Discord bot for Sonarr, Radarr
url: "https://github.com/Calimerorulez/hassio-addons/doplarr"
startup: application
boot: auto
panel_admin: false
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
  
schema:
  server: "match(^.+:\\d+$)"
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
