name: Z-Wave2MQTT Proxy
version: "0.0.2"
panel_icon: "mdi:z-wave"
panel_title: Z-Wave2MQTT
slug: z-wave2mqtt-proxy
description: Proxy addon for Z-Wave2MQTT
url: "https://github.com/Calimerorulez/hassio-addons/z-wave2mqtt-proxy"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8091]/"
watchdog: "http://[HOST]:[PORT:8091]/"
ingress: true
ingress_port: 8091
ingress_entry: /
panel_admin: false
ports:
  8091/tcp: 8091
ports_description:
  8091/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "z-wave2mqtt.local:8091"
schema:
  server: "match(^.+:\\d+$)"
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
