name: ESPHome Proxy Builder

on:
  pull_request:
    branches:
      - main
    paths:
      - "esphome-proxy/**"
      - "nodered-proxy/**"
      - "zwave-js-ui-proxy/**"
      - ".github/workflows/builder.yaml"
      - ".github/workflows/build-app.yaml"

  push:
    branches:
      - main
    paths:
      - "esphome-proxy/**"
      - "nodered-proxy/**"
      - "zwave-js-ui-proxy/**"
      - ".github/workflows/builder.yaml"
      - ".github/workflows/build-app.yaml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-esphome-proxy:
    name: Build ESPHome Proxy
    permissions:
      contents: read
      id-token: write
      packages: write

    uses: ./.github/workflows/build-app.yaml

    with:
      app: esphome-proxy
      publish: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    secrets: inherit

  build-nodered-proxy:
    name: Build Node-RED Proxy
    permissions:
      contents: read
      id-token: write
      packages: write

    uses: ./.github/workflows/build-app.yaml

    with:
      app: nodered-proxy
      publish: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    secrets: inherit

  build-zwave-js-ui-proxy:
    name: Build Z-Wave JS UI Proxy
    permissions:
      contents: read
      id-token: write
      packages: write

    uses: ./.github/workflows/build-app.yaml

    with:
      app: zwave-js-ui-proxy
      publish: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    secrets: inherit
